PAYMENT_PURPOSE_PROGRAM = "program_fee"
PAYMENT_PURPOSE_LEARNING_HUB = "learning_hub"
PAYMENT_PURPOSE_SUBSCRIPTION_ESSENTIAL = "subscription_essential"
PAYMENT_PURPOSE_SUBSCRIPTION_PLUS = "subscription_plus"
PAYMENT_PURPOSE_SUBSCRIPTION_PREMIUM = "subscription_premium"

SUBSCRIPTION_PURPOSES = frozenset({
    PAYMENT_PURPOSE_SUBSCRIPTION_ESSENTIAL,
    PAYMENT_PURPOSE_SUBSCRIPTION_PLUS,
    PAYMENT_PURPOSE_SUBSCRIPTION_PREMIUM,
})

TERMINAL_STATUSES = frozenset({"success", "failed", "cancelled", "timeout"})
