/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScholarshipsRouteImport } from './routes/scholarships'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as OnboardingProcessRouteImport } from './routes/onboarding-process'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as EligibilityRouteImport } from './routes/eligibility'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ScholarshipsSlugRouteImport } from './routes/scholarships.$slug'
import { Route as ResourcesSlugRouteImport } from './routes/resources.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminScholarshipsIndexRouteImport } from './routes/admin/scholarships/index'
import { Route as AdminResourcesIndexRouteImport } from './routes/admin/resources/index'
import { Route as AdminBlogsIndexRouteImport } from './routes/admin/blogs/index'
import { Route as ResourcesModuleModuleIdRouteImport } from './routes/resources.module.$moduleId'
import { Route as PortalAuthVerifyRouteImport } from './routes/portal.auth.verify'
import { Route as AdminScholarshipsNewRouteImport } from './routes/admin/scholarships/new'
import { Route as AdminResourcesNewRouteImport } from './routes/admin/resources/new'
import { Route as AdminBlogsNewRouteImport } from './routes/admin/blogs/new'
import { Route as AdminScholarshipsSlugEditRouteImport } from './routes/admin/scholarships/$slug.edit'
import { Route as AdminResourcesSlugEditRouteImport } from './routes/admin/resources/$slug.edit'
import { Route as AdminBlogsSlugEditRouteImport } from './routes/admin/blogs/$slug.edit'

const ScholarshipsRoute = ScholarshipsRouteImport.update({
  id: '/scholarships',
  path: '/scholarships',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingProcessRoute = OnboardingProcessRouteImport.update({
  id: '/onboarding-process',
  path: '/onboarding-process',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const EligibilityRoute = EligibilityRouteImport.update({
  id: '/eligibility',
  path: '/eligibility',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ScholarshipsSlugRoute = ScholarshipsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ScholarshipsRoute,
} as any)
const ResourcesSlugRoute = ResourcesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ResourcesRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminScholarshipsIndexRoute = AdminScholarshipsIndexRouteImport.update({
  id: '/scholarships/',
  path: '/scholarships/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminResourcesIndexRoute = AdminResourcesIndexRouteImport.update({
  id: '/resources/',
  path: '/resources/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogsIndexRoute = AdminBlogsIndexRouteImport.update({
  id: '/blogs/',
  path: '/blogs/',
  getParentRoute: () => AdminRoute,
} as any)
const ResourcesModuleModuleIdRoute = ResourcesModuleModuleIdRouteImport.update({
  id: '/module/$moduleId',
  path: '/module/$moduleId',
  getParentRoute: () => ResourcesRoute,
} as any)
const PortalAuthVerifyRoute = PortalAuthVerifyRouteImport.update({
  id: '/auth/verify',
  path: '/auth/verify',
  getParentRoute: () => PortalRoute,
} as any)
const AdminScholarshipsNewRoute = AdminScholarshipsNewRouteImport.update({
  id: '/scholarships/new',
  path: '/scholarships/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminResourcesNewRoute = AdminResourcesNewRouteImport.update({
  id: '/resources/new',
  path: '/resources/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogsNewRoute = AdminBlogsNewRouteImport.update({
  id: '/blogs/new',
  path: '/blogs/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminScholarshipsSlugEditRoute =
  AdminScholarshipsSlugEditRouteImport.update({
    id: '/scholarships/$slug/edit',
    path: '/scholarships/$slug/edit',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminResourcesSlugEditRoute = AdminResourcesSlugEditRouteImport.update({
  id: '/resources/$slug/edit',
  path: '/resources/$slug/edit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogsSlugEditRoute = AdminBlogsSlugEditRouteImport.update({
  id: '/blogs/$slug/edit',
  path: '/blogs/$slug/edit',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/eligibility': typeof EligibilityRoute
  '/how-it-works': typeof HowItWorksRoute
  '/onboarding-process': typeof OnboardingProcessRoute
  '/partners': typeof PartnersRoute
  '/portal': typeof PortalRouteWithChildren
  '/register': typeof RegisterRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/scholarships': typeof ScholarshipsRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/scholarships/$slug': typeof ScholarshipsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/admin/blogs/new': typeof AdminBlogsNewRoute
  '/admin/resources/new': typeof AdminResourcesNewRoute
  '/admin/scholarships/new': typeof AdminScholarshipsNewRoute
  '/portal/auth/verify': typeof PortalAuthVerifyRoute
  '/resources/module/$moduleId': typeof ResourcesModuleModuleIdRoute
  '/admin/blogs/': typeof AdminBlogsIndexRoute
  '/admin/resources/': typeof AdminResourcesIndexRoute
  '/admin/scholarships/': typeof AdminScholarshipsIndexRoute
  '/admin/blogs/$slug/edit': typeof AdminBlogsSlugEditRoute
  '/admin/resources/$slug/edit': typeof AdminResourcesSlugEditRoute
  '/admin/scholarships/$slug/edit': typeof AdminScholarshipsSlugEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/eligibility': typeof EligibilityRoute
  '/how-it-works': typeof HowItWorksRoute
  '/onboarding-process': typeof OnboardingProcessRoute
  '/partners': typeof PartnersRoute
  '/portal': typeof PortalRouteWithChildren
  '/register': typeof RegisterRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/scholarships': typeof ScholarshipsRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/scholarships/$slug': typeof ScholarshipsSlugRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/admin/blogs/new': typeof AdminBlogsNewRoute
  '/admin/resources/new': typeof AdminResourcesNewRoute
  '/admin/scholarships/new': typeof AdminScholarshipsNewRoute
  '/portal/auth/verify': typeof PortalAuthVerifyRoute
  '/resources/module/$moduleId': typeof ResourcesModuleModuleIdRoute
  '/admin/blogs': typeof AdminBlogsIndexRoute
  '/admin/resources': typeof AdminResourcesIndexRoute
  '/admin/scholarships': typeof AdminScholarshipsIndexRoute
  '/admin/blogs/$slug/edit': typeof AdminBlogsSlugEditRoute
  '/admin/resources/$slug/edit': typeof AdminResourcesSlugEditRoute
  '/admin/scholarships/$slug/edit': typeof AdminScholarshipsSlugEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/eligibility': typeof EligibilityRoute
  '/how-it-works': typeof HowItWorksRoute
  '/onboarding-process': typeof OnboardingProcessRoute
  '/partners': typeof PartnersRoute
  '/portal': typeof PortalRouteWithChildren
  '/register': typeof RegisterRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/scholarships': typeof ScholarshipsRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/scholarships/$slug': typeof ScholarshipsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/admin/blogs/new': typeof AdminBlogsNewRoute
  '/admin/resources/new': typeof AdminResourcesNewRoute
  '/admin/scholarships/new': typeof AdminScholarshipsNewRoute
  '/portal/auth/verify': typeof PortalAuthVerifyRoute
  '/resources/module/$moduleId': typeof ResourcesModuleModuleIdRoute
  '/admin/blogs/': typeof AdminBlogsIndexRoute
  '/admin/resources/': typeof AdminResourcesIndexRoute
  '/admin/scholarships/': typeof AdminScholarshipsIndexRoute
  '/admin/blogs/$slug/edit': typeof AdminBlogsSlugEditRoute
  '/admin/resources/$slug/edit': typeof AdminResourcesSlugEditRoute
  '/admin/scholarships/$slug/edit': typeof AdminScholarshipsSlugEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/eligibility'
    | '/how-it-works'
    | '/onboarding-process'
    | '/partners'
    | '/portal'
    | '/register'
    | '/resources'
    | '/scholarships'
    | '/admin/login'
    | '/blog/$slug'
    | '/resources/$slug'
    | '/scholarships/$slug'
    | '/admin/'
    | '/blog/'
    | '/admin/blogs/new'
    | '/admin/resources/new'
    | '/admin/scholarships/new'
    | '/portal/auth/verify'
    | '/resources/module/$moduleId'
    | '/admin/blogs/'
    | '/admin/resources/'
    | '/admin/scholarships/'
    | '/admin/blogs/$slug/edit'
    | '/admin/resources/$slug/edit'
    | '/admin/scholarships/$slug/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/eligibility'
    | '/how-it-works'
    | '/onboarding-process'
    | '/partners'
    | '/portal'
    | '/register'
    | '/resources'
    | '/scholarships'
    | '/admin/login'
    | '/blog/$slug'
    | '/resources/$slug'
    | '/scholarships/$slug'
    | '/admin'
    | '/blog'
    | '/admin/blogs/new'
    | '/admin/resources/new'
    | '/admin/scholarships/new'
    | '/portal/auth/verify'
    | '/resources/module/$moduleId'
    | '/admin/blogs'
    | '/admin/resources'
    | '/admin/scholarships'
    | '/admin/blogs/$slug/edit'
    | '/admin/resources/$slug/edit'
    | '/admin/scholarships/$slug/edit'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/eligibility'
    | '/how-it-works'
    | '/onboarding-process'
    | '/partners'
    | '/portal'
    | '/register'
    | '/resources'
    | '/scholarships'
    | '/admin/login'
    | '/blog/$slug'
    | '/resources/$slug'
    | '/scholarships/$slug'
    | '/admin/'
    | '/blog/'
    | '/admin/blogs/new'
    | '/admin/resources/new'
    | '/admin/scholarships/new'
    | '/portal/auth/verify'
    | '/resources/module/$moduleId'
    | '/admin/blogs/'
    | '/admin/resources/'
    | '/admin/scholarships/'
    | '/admin/blogs/$slug/edit'
    | '/admin/resources/$slug/edit'
    | '/admin/scholarships/$slug/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  EligibilityRoute: typeof EligibilityRoute
  HowItWorksRoute: typeof HowItWorksRoute
  OnboardingProcessRoute: typeof OnboardingProcessRoute
  PartnersRoute: typeof PartnersRoute
  PortalRoute: typeof PortalRouteWithChildren
  RegisterRoute: typeof RegisterRoute
  ResourcesRoute: typeof ResourcesRouteWithChildren
  ScholarshipsRoute: typeof ScholarshipsRouteWithChildren
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/scholarships': {
      id: '/scholarships'
      path: '/scholarships'
      fullPath: '/scholarships'
      preLoaderRoute: typeof ScholarshipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding-process': {
      id: '/onboarding-process'
      path: '/onboarding-process'
      fullPath: '/onboarding-process'
      preLoaderRoute: typeof OnboardingProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eligibility': {
      id: '/eligibility'
      path: '/eligibility'
      fullPath: '/eligibility'
      preLoaderRoute: typeof EligibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/scholarships/$slug': {
      id: '/scholarships/$slug'
      path: '/$slug'
      fullPath: '/scholarships/$slug'
      preLoaderRoute: typeof ScholarshipsSlugRouteImport
      parentRoute: typeof ScholarshipsRoute
    }
    '/resources/$slug': {
      id: '/resources/$slug'
      path: '/$slug'
      fullPath: '/resources/$slug'
      preLoaderRoute: typeof ResourcesSlugRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/scholarships/': {
      id: '/admin/scholarships/'
      path: '/scholarships'
      fullPath: '/admin/scholarships/'
      preLoaderRoute: typeof AdminScholarshipsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/resources/': {
      id: '/admin/resources/'
      path: '/resources'
      fullPath: '/admin/resources/'
      preLoaderRoute: typeof AdminResourcesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blogs/': {
      id: '/admin/blogs/'
      path: '/blogs'
      fullPath: '/admin/blogs/'
      preLoaderRoute: typeof AdminBlogsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/resources/module/$moduleId': {
      id: '/resources/module/$moduleId'
      path: '/module/$moduleId'
      fullPath: '/resources/module/$moduleId'
      preLoaderRoute: typeof ResourcesModuleModuleIdRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/portal/auth/verify': {
      id: '/portal/auth/verify'
      path: '/auth/verify'
      fullPath: '/portal/auth/verify'
      preLoaderRoute: typeof PortalAuthVerifyRouteImport
      parentRoute: typeof PortalRoute
    }
    '/admin/scholarships/new': {
      id: '/admin/scholarships/new'
      path: '/scholarships/new'
      fullPath: '/admin/scholarships/new'
      preLoaderRoute: typeof AdminScholarshipsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/resources/new': {
      id: '/admin/resources/new'
      path: '/resources/new'
      fullPath: '/admin/resources/new'
      preLoaderRoute: typeof AdminResourcesNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blogs/new': {
      id: '/admin/blogs/new'
      path: '/blogs/new'
      fullPath: '/admin/blogs/new'
      preLoaderRoute: typeof AdminBlogsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/scholarships/$slug/edit': {
      id: '/admin/scholarships/$slug/edit'
      path: '/scholarships/$slug/edit'
      fullPath: '/admin/scholarships/$slug/edit'
      preLoaderRoute: typeof AdminScholarshipsSlugEditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/resources/$slug/edit': {
      id: '/admin/resources/$slug/edit'
      path: '/resources/$slug/edit'
      fullPath: '/admin/resources/$slug/edit'
      preLoaderRoute: typeof AdminResourcesSlugEditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blogs/$slug/edit': {
      id: '/admin/blogs/$slug/edit'
      path: '/blogs/$slug/edit'
      fullPath: '/admin/blogs/$slug/edit'
      preLoaderRoute: typeof AdminBlogsSlugEditRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminLoginRoute: typeof AdminLoginRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminBlogsNewRoute: typeof AdminBlogsNewRoute
  AdminResourcesNewRoute: typeof AdminResourcesNewRoute
  AdminScholarshipsNewRoute: typeof AdminScholarshipsNewRoute
  AdminBlogsIndexRoute: typeof AdminBlogsIndexRoute
  AdminResourcesIndexRoute: typeof AdminResourcesIndexRoute
  AdminScholarshipsIndexRoute: typeof AdminScholarshipsIndexRoute
  AdminBlogsSlugEditRoute: typeof AdminBlogsSlugEditRoute
  AdminResourcesSlugEditRoute: typeof AdminResourcesSlugEditRoute
  AdminScholarshipsSlugEditRoute: typeof AdminScholarshipsSlugEditRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminLoginRoute: AdminLoginRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminBlogsNewRoute: AdminBlogsNewRoute,
  AdminResourcesNewRoute: AdminResourcesNewRoute,
  AdminScholarshipsNewRoute: AdminScholarshipsNewRoute,
  AdminBlogsIndexRoute: AdminBlogsIndexRoute,
  AdminResourcesIndexRoute: AdminResourcesIndexRoute,
  AdminScholarshipsIndexRoute: AdminScholarshipsIndexRoute,
  AdminBlogsSlugEditRoute: AdminBlogsSlugEditRoute,
  AdminResourcesSlugEditRoute: AdminResourcesSlugEditRoute,
  AdminScholarshipsSlugEditRoute: AdminScholarshipsSlugEditRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface PortalRouteChildren {
  PortalAuthVerifyRoute: typeof PortalAuthVerifyRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalAuthVerifyRoute: PortalAuthVerifyRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

interface ResourcesRouteChildren {
  ResourcesSlugRoute: typeof ResourcesSlugRoute
  ResourcesModuleModuleIdRoute: typeof ResourcesModuleModuleIdRoute
}

const ResourcesRouteChildren: ResourcesRouteChildren = {
  ResourcesSlugRoute: ResourcesSlugRoute,
  ResourcesModuleModuleIdRoute: ResourcesModuleModuleIdRoute,
}

const ResourcesRouteWithChildren = ResourcesRoute._addFileChildren(
  ResourcesRouteChildren,
)

interface ScholarshipsRouteChildren {
  ScholarshipsSlugRoute: typeof ScholarshipsSlugRoute
}

const ScholarshipsRouteChildren: ScholarshipsRouteChildren = {
  ScholarshipsSlugRoute: ScholarshipsSlugRoute,
}

const ScholarshipsRouteWithChildren = ScholarshipsRoute._addFileChildren(
  ScholarshipsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  EligibilityRoute: EligibilityRoute,
  HowItWorksRoute: HowItWorksRoute,
  OnboardingProcessRoute: OnboardingProcessRoute,
  PartnersRoute: PartnersRoute,
  PortalRoute: PortalRouteWithChildren,
  RegisterRoute: RegisterRoute,
  ResourcesRoute: ResourcesRouteWithChildren,
  ScholarshipsRoute: ScholarshipsRouteWithChildren,
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
