/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScholarshipsRouteImport } from './routes/scholarships'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as EligibilityRouteImport } from './routes/eligibility'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ScholarshipsSlugRouteImport } from './routes/scholarships.$slug'
import { Route as ResourcesSlugRouteImport } from './routes/resources.$slug'

const ScholarshipsRoute = ScholarshipsRouteImport.update({
  id: '/scholarships',
  path: '/scholarships',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const EligibilityRoute = EligibilityRouteImport.update({
  id: '/eligibility',
  path: '/eligibility',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScholarshipsSlugRoute = ScholarshipsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ScholarshipsRoute,
} as any)
const ResourcesSlugRoute = ResourcesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ResourcesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/eligibility': typeof EligibilityRoute
  '/how-it-works': typeof HowItWorksRoute
  '/partners': typeof PartnersRoute
  '/portal': typeof PortalRoute
  '/register': typeof RegisterRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/scholarships': typeof ScholarshipsRouteWithChildren
  '/resources/$slug': typeof ResourcesSlugRoute
  '/scholarships/$slug': typeof ScholarshipsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/eligibility': typeof EligibilityRoute
  '/how-it-works': typeof HowItWorksRoute
  '/partners': typeof PartnersRoute
  '/portal': typeof PortalRoute
  '/register': typeof RegisterRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/scholarships': typeof ScholarshipsRouteWithChildren
  '/resources/$slug': typeof ResourcesSlugRoute
  '/scholarships/$slug': typeof ScholarshipsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/eligibility': typeof EligibilityRoute
  '/how-it-works': typeof HowItWorksRoute
  '/partners': typeof PartnersRoute
  '/portal': typeof PortalRoute
  '/register': typeof RegisterRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/scholarships': typeof ScholarshipsRouteWithChildren
  '/resources/$slug': typeof ResourcesSlugRoute
  '/scholarships/$slug': typeof ScholarshipsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/eligibility'
    | '/how-it-works'
    | '/partners'
    | '/portal'
    | '/register'
    | '/resources'
    | '/scholarships'
    | '/resources/$slug'
    | '/scholarships/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/eligibility'
    | '/how-it-works'
    | '/partners'
    | '/portal'
    | '/register'
    | '/resources'
    | '/scholarships'
    | '/resources/$slug'
    | '/scholarships/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/eligibility'
    | '/how-it-works'
    | '/partners'
    | '/portal'
    | '/register'
    | '/resources'
    | '/scholarships'
    | '/resources/$slug'
    | '/scholarships/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  EligibilityRoute: typeof EligibilityRoute
  HowItWorksRoute: typeof HowItWorksRoute
  PartnersRoute: typeof PartnersRoute
  PortalRoute: typeof PortalRoute
  RegisterRoute: typeof RegisterRoute
  ResourcesRoute: typeof ResourcesRouteWithChildren
  ScholarshipsRoute: typeof ScholarshipsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/scholarships': {
      id: '/scholarships'
      path: '/scholarships'
      fullPath: '/scholarships'
      preLoaderRoute: typeof ScholarshipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eligibility': {
      id: '/eligibility'
      path: '/eligibility'
      fullPath: '/eligibility'
      preLoaderRoute: typeof EligibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scholarships/$slug': {
      id: '/scholarships/$slug'
      path: '/$slug'
      fullPath: '/scholarships/$slug'
      preLoaderRoute: typeof ScholarshipsSlugRouteImport
      parentRoute: typeof ScholarshipsRoute
    }
    '/resources/$slug': {
      id: '/resources/$slug'
      path: '/$slug'
      fullPath: '/resources/$slug'
      preLoaderRoute: typeof ResourcesSlugRouteImport
      parentRoute: typeof ResourcesRoute
    }
  }
}

interface ResourcesRouteChildren {
  ResourcesSlugRoute: typeof ResourcesSlugRoute
}

const ResourcesRouteChildren: ResourcesRouteChildren = {
  ResourcesSlugRoute: ResourcesSlugRoute,
}

const ResourcesRouteWithChildren = ResourcesRoute._addFileChildren(
  ResourcesRouteChildren,
)

interface ScholarshipsRouteChildren {
  ScholarshipsSlugRoute: typeof ScholarshipsSlugRoute
}

const ScholarshipsRouteChildren: ScholarshipsRouteChildren = {
  ScholarshipsSlugRoute: ScholarshipsSlugRoute,
}

const ScholarshipsRouteWithChildren = ScholarshipsRoute._addFileChildren(
  ScholarshipsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  EligibilityRoute: EligibilityRoute,
  HowItWorksRoute: HowItWorksRoute,
  PartnersRoute: PartnersRoute,
  PortalRoute: PortalRoute,
  RegisterRoute: RegisterRoute,
  ResourcesRoute: ResourcesRouteWithChildren,
  ScholarshipsRoute: ScholarshipsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
